broker.id=5
zookeeper.connect=kafka-4:2181,kafka-5:2181,kafka-6:2181
listeners=SASL_SSL://0.0.0.0:9093,SASL_PLAINTEXT://0.0.0.0:29092
advertised.listeners=SASL_PLAINTEXT://kafka-5:29092,SASL_SSL://kafka-5:9093
listener.security.protocol.map=SASL_SSL:SASL_SSL,SASL_PLAINTEXT:SASL_PLAINTEXT
inter.broker.listener.name=SASL_SSL
sasl.enabled.mechanisms=SCRAM-SHA-512
sasl.mechanism.inter.broker.protocol=SCRAM-SHA-512
listener.name.sasl_ssl.scram-sha-512.sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username="interbroker" password="interbroker-secret";
authorizer.class.name=kafka.security.authorizer.AclAuthorizer
allow.everyone.if.no.acl.found=false
super.users=User:admin;User:interbroker
ssl.keystore.location=/opt/kafka/certs/kafka-5.keystore.jks
ssl.keystore.password=changeit
ssl.key.password=changeit
ssl.truststore.location=/opt/kafka/certs/kafka.truststore.jks
ssl.truststore.password=changeit
ssl.client.auth=required
offsets.topic.replication.factor=3
group.initial.rebalance.delay.ms=0
transaction.state.log.min.isr=2
transaction.state.log.replication.factor=3
min.insync.replicas=2
log.dirs=/tmp/kafka-logs
zookeeper.connection.timeout.ms=60000
default.replication.factor=3
num.partitions=3