dataDir=/tmp/zookeeper
clientPort=2181
maxClientCnxns=0
admin.enableServer=false
tickTime=2000
initLimit=10
syncLimit=5
4lw.commands.whitelist=*
server.4=kafka-4:2888:3888
server.5=kafka-5:2888:3888
server.6=kafka-6:2888:3888