# Конвертеры
key.converter=org.apache.kafka.connect.converters.ByteArrayConverter
value.converter=org.apache.kafka.connect.converters.ByteArrayConverter

# Файлы состояния для standalone режима
offset.storage.file.filename=/tmp/connect.offsets
config.storage.file.filename=/tmp/connect.configs
status.storage.file.filename=/tmp/connect.status

clusters = primary, secondary

primary.bootstrap.servers = kafka-1:29092,kafka-2:29092,kafka-3:29092
primary.security.protocol = SASL_PLAINTEXT
primary.sasl.mechanism = SCRAM-SHA-512
primary.sasl.jaas.config = org.apache.kafka.common.security.scram.ScramLoginModule required username="mm2" password="mm2-secret";

secondary.bootstrap.servers = kafka-4:29092,kafka-5:29092,kafka-6:29092
secondary.security.protocol = SASL_PLAINTEXT
secondary.sasl.mechanism = SCRAM-SHA-512
secondary.sasl.jaas.config = org.apache.kafka.common.security.scram.ScramLoginModule required username="mm2" password="mm2-secret";

primary->secondary.enabled = true
secondary->primary.enabled = true

primary->secondary.topics = .*
primary->secondary.topics.exclude = ^test$,.*connect.*,.*/primary\..*,.*/secondary\..*,.*mm2.*
secondary->primary.topics = .*
secondary->primary.topics.exclude = ^test$,.*connect.*,.*/primary\..*,.*/secondary\..*,.*mm2.*

primary->secondary.groups = .*
secondary->primary.groups = .*
primary->secondary.groups.exclude = .*mm2.*
secondary->primary.groups.exclude = .*mm2.*

primary->secondary.emit.heartbeats.enabled = true
secondary->primary.emit.heartbeats.enabled = true

refresh.topics.interval.seconds = 10
refresh.groups.interval.seconds = 10

primary->secondary.sync.topic.configs.enabled = false
secondary->primary.sync.topic.configs.enabled = false

primary->secondary.offset-syncs.topic.replication.factor = 3
secondary->primary.offset-syncs.topic.replication.factor = 3