# Глобальные настройки worker'а (подключение к secondary для внутренних топиков)
bootstrap.servers = kafka-4:29092,kafka-5:29092,kafka-6:29092
security.protocol = SASL_PLAINTEXT
sasl.mechanism = SCRAM-SHA-512
sasl.jaas.config = org.apache.kafka.common.security.scram.ScramLoginModule required username="mm2" password="mm2-secret";

group.id = secondary-mm2

clusters = primary, secondary

primary.bootstrap.servers = kafka-1:29092,kafka-2:29092,kafka-3:29092
primary.security.protocol = SASL_PLAINTEXT
primary.sasl.mechanism = SCRAM-SHA-512
primary.sasl.jaas.config = org.apache.kafka.common.security.scram.ScramLoginModule required username="mm2" password="mm2-secret";

secondary.bootstrap.servers = kafka-4:29092,kafka-5:29092,kafka-6:29092
secondary.security.protocol = SASL_PLAINTEXT
secondary.sasl.mechanism = SCRAM-SHA-512
secondary.sasl.jaas.config = org.apache.kafka.common.security.scram.ScramLoginModule required username="mm2" password="mm2-secret";

secondary->primary.enabled = true

secondary->primary.topics = .*
secondary->primary.topics.exclude = ^test$,.*connect.*,primary\.connect.*,secondary\.connect.*,.*/primary\\..*,.*/secondary\\..*,.*mm2.*,__.*
secondary->primary.topics.replication.policy.class = org.apache.kafka.connect.mirror.DefaultReplicationPolicy

secondary->primary.sync.topic.partitions.enabled = true
secondary->primary.sync.topic.partitions.interval.seconds = 60
secondary->primary.sync.topic.config.enabled = true
secondary->primary.sync.topic.config.interval.seconds = 60
secondary->primary.sync.group.offsets.enabled = true
secondary->primary.sync.group.offsets.interval.seconds = 60

heartbeats.topic.name = heartbeats
heartbeats.topic.replication.factor = 3
secondary->primary.heartbeats.enabled = true
checkpoints.topic.name = checkpoints
checkpoints.topic.replication.factor = 3
secondary->primary.checkpoints.enabled = true

secondary->primary.tasks = 3
secondary->primary.consumer.fetch.min.bytes = 1
secondary->primary.consumer.fetch.max.wait.ms = 1000
secondary->primary.consumer.auto.offset.reset = earliest
secondary->primary.consumer.poll.timeout.ms = 1000

offset.storage.topic = secondary.connect-offsets
offset.storage.replication.factor = 3
offset.storage.partitions = 25
config.storage.topic = secondary.connect-configs
config.storage.replication.factor = 3
status.storage.topic = secondary.connect-status
status.storage.replication.factor = 3
status.storage.partitions = 5
offset.flush.interval.ms = 10000

key.converter = org.apache.kafka.connect.storage.StringConverter
value.converter = org.apache.kafka.connect.storage.StringConverter

rest.port = 8083

secondary->primary.connector.class = org.apache.kafka.connect.mirror.MirrorSourceConnector