# Глобальные настройки worker'а (подключение к primary для внутренних топиков)
bootstrap.servers = kafka-1:29092,kafka-2:29092,kafka-3:29092
security.protocol = SASL_PLAINTEXT
sasl.mechanism = SCRAM-SHA-512
sasl.jaas.config = org.apache.kafka.common.security.scram.ScramLoginModule required username="mm2" password="mm2-secret";

group.id = primary-mm2

clusters = primary, secondary

primary.bootstrap.servers = kafka-1:29092,kafka-2:29092,kafka-3:29092
primary.security.protocol = SASL_PLAINTEXT
primary.sasl.mechanism = SCRAM-SHA-512
primary.sasl.jaas.config = org.apache.kafka.common.security.scram.ScramLoginModule required username="mm2" password="mm2-secret";

secondary.bootstrap.servers = kafka-4:29092,kafka-5:29092,kafka-6:29092
secondary.security.protocol = SASL_PLAINTEXT
secondary.sasl.mechanism = SCRAM-SHA-512
secondary.sasl.jaas.config = org.apache.kafka.common.security.scram.ScramLoginModule required username="mm2" password="mm2-secret";

primary->secondary.enabled = true

primary->secondary.topics = .*
primary->secondary.topics.exclude = ^test$,.*connect.*,primary\.connect.*,secondary\.connect.*,.*/primary\\..*,.*/secondary\\..*,.*mm2.*,__.*
primary->secondary.topics.replication.policy.class = org.apache.kafka.connect.mirror.DefaultReplicationPolicy

primary->secondary.sync.topic.partitions.enabled = true
primary->secondary.sync.topic.partitions.interval.seconds = 60
primary->secondary.sync.topic.config.enabled = true
primary->secondary.sync.topic.config.interval.seconds = 60
primary->secondary.sync.group.offsets.enabled = true
primary->secondary.sync.group.offsets.interval.seconds = 60

heartbeats.topic.name = heartbeats
heartbeats.topic.replication.factor = 3
primary->secondary.heartbeats.enabled = true
checkpoints.topic.name = checkpoints
checkpoints.topic.replication.factor = 3
primary->secondary.checkpoints.enabled = true

primary->secondary.tasks = 3
primary->secondary.consumer.fetch.min.bytes = 1
primary->secondary.consumer.fetch.max.wait.ms = 1000
primary->secondary.consumer.auto.offset.reset = earliest
primary->secondary.consumer.poll.timeout.ms = 1000

offset.storage.topic = primary.connect-offsets
offset.storage.replication.factor = 3
offset.storage.partitions = 25
config.storage.topic = primary.connect-configs
config.storage.replication.factor = 3
status.storage.topic = primary.connect-status
status.storage.replication.factor = 3
status.storage.partitions = 5
offset.flush.interval.ms = 10000

key.converter = org.apache.kafka.connect.storage.StringConverter
value.converter = org.apache.kafka.connect.storage.StringConverter

rest.port = 8083

primary->secondary.connector.class = org.apache.kafka.connect.mirror.MirrorSourceConnector